name: shahihmuslim
description: "Sahih Muslim — Production Hadith App"
publish_to: 'none'
version: 1.4.2+7

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.5.1
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  path: ^1.9.1
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  shimmer: ^3.0.0
  sqflite_common_ffi: ^2.4.0+2
  sqflite_common_ffi_web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  build_runner: 2.4.13
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A237E"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#1A237E"
  image: assets/icon/icon_circle.png
  android_12:
    image: assets/icon/icon_circle.png
    color: "#1A237E"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/db/
    - assets/icon/
