// Hadith data: [chapterId, hadithNumber, arabic, urdu, english]
// Representative hadiths per chapter (authentic from Sahih Muslim)
const hadithData = [
// Ch1 Revelation
[1,1,'إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى','اعمال کا دارومدار نیتوں پر ہے اور ہر شخص کو وہی ملے گا جس کی اس نے نیت کی۔','The reward of deeds depends upon the intentions and every person will get the reward according to what he has intended.'],
[1,2,'أول ما بدئ به رسول الله ﷺ من الوحي الرؤيا الصالحة في النوم','نبی ﷺ پر وحی کی ابتداء سچے خوابوں سے ہوئی۔','The commencement of Divine Inspiration was in the form of good dreams which came true like bright daylight.'],
[1,3,'أحيانا يأتيني مثل صلصلة الجرس وهو أشده علي','کبھی وحی گھنٹی کی آواز کی طرح آتی ہے اور یہ مجھ پر سب سے سخت ہوتی ہے۔','Sometimes it is revealed like the ringing of a bell, this form of Inspiration is the hardest of all.'],
[1,4,'فجاءه الحق وهو في غار حراء، فجاءه الملك فقال: اقرأ','آپ ﷺ غار حراء میں تھے کہ فرشتے نے کہا: پڑھو!','The Truth came to him while he was in the cave of Hira. The angel said Read!'],
[1,5,'فرجع بها رسول الله ﷺ يرجف فؤاده فدخل على خديجة فقال: زملوني زملوني','رسول اللہ ﷺ اپنے دل کانپتے ہوئے واپس آئے اور فرمایا: مجھے کمبل اڑھا دو۔','Allah Messenger returned with his heart beating severely and said Cover me! Cover me!'],
[1,6,'فقالت خديجة: كلا والله ما يخزيك الله أبدا','خدیجہ نے فرمایا: نہیں! اللہ کی قسم اللہ آپ کو کبھی رسوا نہیں کرے گا۔','Khadija replied Never! By Allah Allah will never disgrace you.'],
[1,7,'ثم لم ينشب ورقة أن توفي وفتر الوحي','اس کے بعد ورقہ کا انتقال ہو گیا اور وحی بند ہو گئی۔','After that Waraqa passed away and the Divine Inspiration was paused for a while.'],
// Ch2 Faith
[2,8,'بني الإسلام على خمس: شهادة أن لا إله إلا الله وأن محمدا رسول الله وإقام الصلاة وإيتاء الزكاة والحج وصوم رمضان','اسلام کی بنیاد پانچ چیزوں پر ہے: شہادتین، نماز، زکوٰۃ، حج اور روزے۔','Islam is based on five things: testifying that there is no god but Allah, offering prayers, paying Zakat, performing Hajj, and fasting during Ramadan.'],
[2,9,'المسلم من سلم المسلمون من لسانه ويده','مسلمان وہ ہے جس کی زبان اور ہاتھ سے دوسرے مسلمان محفوظ رہیں۔','A Muslim is the one who avoids harming Muslims with his tongue and hands.'],
[2,10,'أفضل الإسلام أن تطعم الطعام وتقرأ السلام على من عرفت ومن لم تعرف','اسلام کا سب سے بہتر عمل یہ ہے کہ کھانا کھلاؤ اور سلام کرو۔','The best thing in Islam is to feed others and to say Salam to those you know and those you do not know.'],
[2,11,'لا يؤمن أحدكم حتى أكون أحب إليه من والده وولده والناس أجمعين','تم میں سے کوئی مومن نہیں جب تک میں اسے سب سے زیادہ محبوب نہ ہو جاؤں۔','None of you will have faith till he loves me more than his father his children and all mankind.'],
[2,12,'ثلاث من كن فيه وجد بهن حلاوة الإيمان','تین خصلتیں جن میں پائی جائیں اسے ایمان کی مٹھاس مل جاتی ہے۔','Whoever possesses three qualities will have the sweetness of faith.'],
// Ch3 Knowledge
[3,13,'من يرد الله به خيرا يفقهه في الدين','جس کے ساتھ اللہ بھلائی کا ارادہ فرماتا ہے اسے دین کی سمجھ دے دیتا ہے۔','If Allah wants to do good to a person He makes him comprehend the religion.'],
[3,14,'بلغوا عني ولو آية','میری بات پہنچاؤ خواہ ایک آیت ہی ہو۔','Convey my teachings to the people even if it were a single sentence.'],
[3,15,'من سلك طريقا يلتمس فيه علما سهل الله له به طريقا إلى الجنة','جو شخص علم کے لیے راستے پر چلے اللہ اس کے لیے جنت کا راستہ آسان کر دے۔','Whoever follows a path in pursuit of knowledge Allah will make easy for him a path to Paradise.'],
[3,16,'إن الله لا يقبض العلم انتزاعا ينتزعه من العباد ولكن يقبض العلم بقبض العلماء','اللہ علم کو بندوں سے چھین کر نہیں اٹھائے گا بلکہ علماء کو اٹھا کر علم اٹھائے گا۔','Allah does not take away knowledge by taking it from the people but takes it by the death of the learned men.'],
// Ch4 Wudu
[4,17,'لا تقبل صلاة بغير طهور','بغیر وضو نماز قبول نہیں ہوتی۔','No prayer is accepted without purification.'],
[4,18,'مفتاح الصلاة الطهور وتحريمها التكبير وتحليلها التسليم','نماز کی کنجی پاکیزگی ہے اس کی تحریم تکبیر اور تحلیل سلام ہے۔','The key to prayer is cleanliness its beginning is Takbir and its end is Salam.'],
[4,19,'إذا توضأ أحدكم فليستنشق بمنخريه من الماء','جب تم میں سے کوئی وضو کرے تو ناک میں پانی ڈالے۔','When anyone performs ablution he should put water in his nostrils and then blow it out.'],
// Ch5 Ghusl
[5,20,'إذا جلس بين شعبها الأربع ثم جهدها فقد وجب الغسل','جب آدمی عورت کے چاروں شعبوں کے درمیان بیٹھے تو غسل واجب ہو جاتا ہے۔','When a man sits between the four parts of a woman and exerts himself bathing becomes obligatory.'],
[5,21,'كان رسول الله ﷺ يغتسل بالصاع','رسول اللہ ﷺ ایک صاع پانی سے غسل فرماتے تھے۔','The Prophet used to take bath with one Saa of water.'],
// Ch6 Menstrual Periods
[6,22,'إن هذا شيء كتبه الله على بنات آدم','یہ ایسی چیز ہے جو اللہ نے آدم کی بیٹیوں پر لکھ دی ہے۔','This is a thing which Allah has ordained for the daughters of Adam.'],
[6,23,'افعلي ما يفعل الحاج غير أن لا تطوفي بالبيت حتى تطهري','حج کے سارے کام کرو مگر طواف نہ کرو جب تک پاک نہ ہو جاؤ۔','Perform all the ceremonies of Hajj but do not perform Tawaf until you become clean.'],
// Ch7 Tayammum
[7,24,'جعلت لي الأرض مسجدا وطهورا','میرے لیے زمین مسجد اور پاک کرنے والی بنائی گئی ہے۔','The earth has been made for me a place for praying and a thing to purify.'],
[7,25,'الصعيد الطيب وضوء المسلم وإن لم يجد الماء عشر سنين','پاک مٹی مسلمان کا وضو ہے خواہ دس سال تک پانی نہ ملے۔','Clean earth is sufficient for purification even if he does not find water for ten years.'],
// Ch8 Prayers
[8,26,'صلوا كما رأيتموني أصلي','نماز ویسے پڑھو جیسے تم مجھے پڑھتے دیکھتے ہو۔','Pray as you have seen me praying.'],
[8,27,'بين الرجل وبين الشرك والكفر ترك الصلاة','آدمی اور شرک کے درمیان فرق نماز چھوڑنا ہے۔','Between a man and polytheism and disbelief is the abandonment of prayer.'],
[8,28,'أول ما يحاسب به العبد يوم القيامة صلاته','قیامت کے دن سب سے پہلے نماز کا حساب ہو گا۔','The first thing that the servant will be called to account for on the Day of Judgment will be the prayer.'],
// Ch9 Times of Prayer
[9,29,'فضل صلاة الجماعة على صلاة الفذ سبع وعشرون درجة','جماعت کی نماز اکیلے نماز سے ستائیس درجے افضل ہے۔','The prayer in congregation is twenty-seven times superior to the prayer offered alone.'],
[9,30,'إذا أقيمت الصلاة فلا تأتوها تسعون وأتوها تمشون','جب نماز کھڑی ہو جائے تو دوڑتے ہوئے نہ آؤ بلکہ چل کر آؤ۔','When the prayer is started do not come to it running but walk with calmness.'],
// Ch10 Adhan
[10,31,'إذا سمعتم المؤذن فقولوا مثل ما يقول','جب مؤذن کی آواز سنو تو اسی طرح کہو جو مؤذن کہتا ہے۔','When you hear the Muadhdhin repeat what he says.'],
[10,32,'الإمام ضامن والمؤذن مؤتمن','امام ذمہ دار ہے اور مؤذن امانتدار ہے۔','The Imam is appointed to be followed and the Muadhdhin is trusted.'],
// Ch11-20
[11,33,'من ترك الجمعة ثلاث مرات تهاونا طبع الله على قلبه','جس نے تین جمعے سستی سے چھوڑے اللہ اس کے دل پر مہر لگا دے گا۔','Whoever misses three Friday prayers out of negligence Allah will seal his heart.'],
[12,34,'صلاة الخوف أن تقوم طائفة منهم معه وطائفة وجاه العدو','خوف کی نماز یہ ہے کہ ایک جماعت تمہارے ساتھ نماز پڑھے اور ایک دشمن کے سامنے ہو۔','Fear prayer is that one group prays with you while the other faces the enemy.'],
[13,35,'عيدان اجتمعا في يومكم هذا فمن شاء أجزأه من الجمعة','آج تمہارے لیے دو عیدیں جمع ہو گئی ہیں جو چاہے جمعہ نہ آئے۔','Two Eids have coincided on this day so whoever wishes may skip Friday prayer.'],
[14,36,'اجعلوا آخر صلاتكم بالليل وترا','رات کی آخری نماز وتر بناؤ۔','Make Witr as the last prayer of the night.'],
[15,37,'اللهم اسقنا غيثا مغيثا مريئا نافعا غير ضار عاجلا غير آجل','اے اللہ ہمیں فائدہ مند بارش سے سیراب فرما۔','O Allah send us rain beneficial not harmful soon not delayed.'],
[16,38,'إن الشمس والقمر لا ينكسفان لموت أحد ولا لحياته','سورج اور چاند کسی کی موت یا زندگی سے نہیں گرہن لگتا۔','The sun and the moon do not eclipse because of someones death or life.'],
[17,39,'كان النبي ﷺ يقرأ في السجدة: اقرأ باسم ربك','نبی ﷺ سجدے میں اقرأ باسم ربک پڑھتے تھے۔','The Prophet used to recite in Sajdah Read in the name of your Lord.'],
[18,40,'كان النبي ﷺ يقصر في السفر ويفطر','نبی ﷺ سفر میں نماز قصر کرتے اور روزہ چھوڑتے تھے۔','The Prophet used to shorten the prayers and break fasts during travel.'],
[19,41,'أفضل الصلاة بعد الفريضة صلاة الليل','فرض نماز کے بعد سب سے افضل نماز تہجد ہے۔','The best prayer after the obligatory is the night prayer.'],
[20,42,'صلاة في مسجدي هذا أفضل من ألف صلاة فيما سواه إلا المسجد الحرام','میری اس مسجد میں نماز ہزار نمازوں سے افضل ہے سوائے مسجد الحرام کے۔','One prayer in my mosque is better than a thousand prayers in any other mosque except Al-Masjid Al-Haram.'],
// Ch21-40
[21,43,'من أحدث في صلاته فليأخذ بأنفه ولينصرف','جس کا نماز میں وضو ٹوٹ جائے وہ ناک پکڑ کر چلا جائے۔','If one has the urge to pass wind during prayer hold your nose and leave.'],
[22,44,'إذا شك أحدكم في صلاته فليبن على ما استيقن','جب تم میں سے کسی کو نماز میں شک ہو تو یقین والی تعداد پر بنا کرے۔','If anyone has doubt in prayer he should build upon what he is sure of.'],
[23,45,'صلوا على صاحبكم','اپنے ساتھی کی نماز جنازہ پڑھو۔','Offer the funeral prayer for your companion.'],
[23,46,'ما من مسلم يموت فيقوم على جنازته أربعون رجلا لا يشركون بالله شيئا إلا شفعهم الله فيه','جب کوئی مسلمان فوت ہو اور چالیس آدمی جنازہ پڑھیں جو شرک نہ کرتے ہوں تو اللہ ان کی شفاعت قبول فرمائے۔','If a Muslim dies and forty men who do not associate anything with Allah offer his funeral prayer Allah will accept their intercession.'],
[24,47,'ما من صاحب ذهب ولا فضة لا يؤدي منها حقها إلا صفحت له يوم القيامة صفائح من نار','جو سونے چاندی کا مالک ان کا حق ادا نہ کرے اسے آگ کی تختیاں بنا کر داغا جائے گا۔','Whoever has gold or silver and does not pay Zakat it will be heated as plates of fire in Hell.'],
[25,48,'من حج فلم يرفث ولم يفسق رجع كيوم ولدته أمه','جس نے حج کیا اور فحش باتیں اور گناہ نہ کیے وہ ایسے لوٹتا ہے جیسے ماں نے جنا۔','Whoever performs Hajj and does not indulge in obscenity or sin returns like a newborn.'],
[26,49,'العمرة إلى العمرة كفارة لما بينهما','ایک عمرہ سے دوسرے عمرہ تک درمیان کے گناہوں کا کفارہ ہے۔','The performance of Umrah is an expiation for sins committed between it and the previous one.'],
[27,50,'من كسر أو عرج فقد حل وعليه حجة أخرى','جس کا ہڈی ٹوٹ جائے یا لنگڑا ہو جائے وہ احرام کھول دے اور دوبارہ حج کرے۔','Whoever breaks a bone or becomes lame may remove Ihram and must perform Hajj again.'],
[28,51,'من قتل حيوانا من الصيد وهو محرم فعليه جزاؤه','جو شخص احرام میں شکار مارے اس پر فدیہ واجب ہے۔','Whoever kills game while in Ihram must pay its penalty.'],
[29,52,'اللهم بارك لنا في مدينتنا','اے اللہ ہمارے مدینے میں برکت دے۔','O Allah bless our Madinah.'],
[30,53,'من صام رمضان إيمانا واحتسابا غفر له ما تقدم من ذنبه','جس نے ایمان و ثواب کی نیت سے رمضان کے روزے رکھے اس کے پچھلے گناہ معاف ہو جائیں گے۔','Whoever fasts Ramadan with faith and seeking reward his previous sins will be forgiven.'],
[30,54,'صوموا لرؤيته وأفطروا لرؤيته','چاند دیکھ کر روزہ رکھو اور چاند دیکھ کر افطار کرو۔','Fast when you see the crescent moon and break fast when you see it.'],
[31,55,'من قام رمضان إيمانا واحتسابا غفر له ما تقدم من ذنبه','جس نے ایمان اور ثواب کی نیت سے رمضان میں قیام کیا اس کے پچھلے گناہ معاف ہو جائیں گے۔','Whoever prays during the nights of Ramadan with faith his previous sins will be forgiven.'],
[32,56,'تحروا ليلة القدر في الوتر من العشر الأواخر من رمضان','شب قدر کو رمضان کی آخری دس طاق راتوں میں تلاش کرو۔','Search for Laylat ul-Qadr in the odd nights of the last ten days of Ramadan.'],
[33,57,'من اعتكف بإيمان واحتساب غفر له ما تقدم من ذنبه','جس نے ایمان اور ثواب کی نیت سے اعتکاف کیا اس کے پچھلے گناہ معاف ہو جائیں گے۔','Whoever performs Itikaf with faith his previous sins will be forgiven.'],
[34,58,'البيعان بالخيار ما لم يتفرقا','خریدار اور بیچنے والے کو اختیار ہے جب تک جدا نہ ہوں۔','The buyer and seller have the option of cancelling as long as they have not parted.'],
[35,59,'من أسلم في شيء فليسلم في كيل معلوم ووزن معلوم إلى أجل معلوم','جو سلم کرے تو معلوم ناپ تول اور معلوم مدت پر کرے۔','Whoever pays in advance should pay for a specified measure and weight for a specified period.'],
[36,60,'الشفعة في كل ما لم يقسم','شفعہ ہر اس چیز میں ہے جو تقسیم نہ ہوئی ہو۔','Pre-emption applies to everything that has not been divided.'],
[37,61,'أعطوا الأجير أجره قبل أن يجف عرقه','مزدور کو اس کا پسینہ خشک ہونے سے پہلے اس کی اجرت دے دو۔','Pay the worker his wages before his sweat dries.'],
[38,62,'المسلم أخو المسلم لا يظلمه ولا يسلمه','مسلمان مسلمان کا بھائی ہے نہ اس پر ظلم کرے نہ اسے حوالے کرے۔','A Muslim is a brother of another Muslim. He should not oppress him nor should he hand him over.'],
[39,63,'الزعيم غارم','ضامن ذمہ دار ہے۔','The guarantor is responsible.'],
[40,64,'لا ضرر ولا ضرار','نقصان پہنچانا اور نقصان کا بدلہ لینا دونوں ممنوع ہیں۔','There should be no harm nor reciprocal harm.'],
// Ch41-60
[41,65,'ما من مسلم يغرس غرسا أو يزرع زرعا فيأكل منه طير أو إنسان إلا كان له به صدقة','جو مسلمان درخت لگائے یا کھیتی کرے اور اس سے پرندہ یا انسان کھائے تو یہ اس کے لیے صدقہ ہے۔','There is none amongst the Muslims who plants a tree or sows seeds and then a bird or animal eats from it but is regarded as a charitable gift for him.'],
[42,66,'الناس شركاء في ثلاث: الماء والكلإ والنار','لوگ تین چیزوں میں شریک ہیں: پانی، چراگاہ اور آگ۔','People are partners in three things: water pasture and fire.'],
[43,67,'من أخذ أموال الناس يريد أداءها أدى الله عنه ومن أخذ يريد إتلافها أتلفه الله','جو لوگوں کا مال واپسی کی نیت سے لے اللہ اس کی طرف سے ادا کرے اور جو ضائع کرنے کی نیت سے لے اللہ اسے برباد کرے۔','Whoever takes peoples money intending to repay it Allah will repay on his behalf. Whoever takes it to waste Allah will waste him.'],
[44,68,'لو يعطى الناس بدعواهم لادعى ناس دماء رجال وأموالهم','اگر لوگوں کو ان کے دعوے سے دے دیا جائے تو لوگ خون اور مال کا دعویٰ کر بیٹھیں۔','If people were given based on their claims they would claim blood and money of others.'],
[45,69,'من وجد لقطة فليشهد ذا عدل','جو گری ہوئی چیز پائے تو عادل گواہ بنائے۔','Whoever picks up a lost article should call a just witness.'],
[46,70,'اتقوا الظلم فإن الظلم ظلمات يوم القيامة','ظلم سے بچو کیونکہ ظلم قیامت کے دن اندھیرا ہے۔','Beware of oppression for oppression will be darkness on the Day of Resurrection.'],
[47,71,'إذا اختلف المتبايعان فالقول قول البائع','جب خریدار اور بیچنے والے میں اختلاف ہو تو بیچنے والے کی بات مانی جائے۔','When the buyer and seller disagree the statement of the seller is accepted.'],
[48,72,'نهى رسول الله ﷺ عن بيع الغرر','رسول اللہ ﷺ نے دھوکے کی بیع سے منع فرمایا۔','The Prophet forbade the sale involving uncertainty.'],
[49,73,'من أعتق رقبة مسلمة أعتق الله بكل عضو منها عضوا منه من النار','جس نے مسلمان غلام آزاد کیا اللہ اس کے ہر عضو کے بدلے آگ سے بچائے۔','Whoever frees a Muslim slave Allah will free each part of his body from the Fire.'],
[50,74,'المكاتب عبد ما بقي عليه من مكاتبته درهم','مکاتب غلام ہے جب تک اس پر ایک درہم بھی باقی ہے۔','A Mukatab remains a slave as long as a single Dirham is due.'],
[51,75,'تهادوا تحابوا','آپس میں تحائف دو محبت بڑھے گی۔','Exchange gifts and you will love one another.'],
[52,76,'من كتم شهادة فإنه آثم قلبه','جس نے گواہی چھپائی اس کا دل گنہگار ہے۔','Whoever conceals testimony his heart is sinful.'],
[53,77,'الصلح جائز بين المسلمين إلا صلحا حرم حلالا أو أحل حراما','مسلمانوں کے درمیان صلح جائز ہے سوائے اس کے جو حلال کو حرام یا حرام کو حلال کرے۔','Reconciliation is allowed among Muslims except that which makes lawful unlawful or vice versa.'],
[54,78,'المؤمنون عند شروطهم','مومن اپنی شرائط پر قائم رہتے ہیں۔','The believers are bound by their conditions.'],
[55,79,'لا وصية لوارث','وارث کے لیے وصیت نہیں۔','There is no bequest for an heir.'],
[56,80,'الجنة تحت ظلال السيوف','جنت تلواروں کے سائے میں ہے۔','Paradise is under the shades of swords.'],
[57,81,'الخمس في خمسة أشياء','خمس پانچ چیزوں میں ہے۔','The Khumus is in five things.'],
[58,82,'من عاهد قوما فلا يحل له إلا أن ينبذ إليهم عهدهم','جس نے کسی قوم سے عہد کیا وہ نہ توڑے مگر اعلان کے ساتھ۔','Whoever has a treaty with people it is not legal to break it without notice.'],
[59,83,'خلق الله آدم على صورته','اللہ نے آدم کو اپنی شکل پر بنایا۔','Allah created Adam in His image.'],
[60,84,'ما بعث الله من نبي إلا رعى الغنم','اللہ نے جتنے بھی نبی بھیجے سب نے بکریاں چرائیں۔','There was no prophet who was not a shepherd.'],
// Ch61-80
[61,85,'خير الناس قرني ثم الذين يلونهم ثم الذين يلونهم','سب سے بہتر زمانہ میرا ہے پھر اس کے بعد والا پھر اس کے بعد والا۔','The best people are those of my generation then those who come after them then those who come after them.'],
[62,86,'لا تسبوا أصحابي فلو أن أحدكم أنفق مثل أحد ذهبا ما بلغ مد أحدهم ولا نصيفه','میرے صحابہ کو برا نہ کہو اگر تم احد پہاڑ جتنا سونا خرچ کرو تو ان کے ایک مد کے برابر نہ ہو۔','Do not abuse my companions for if any one of you spent gold equal to Uhud it would not equal a handful of one of them.'],
[63,87,'لولا الهجرة لكنت امرأ من الأنصار','اگر ہجرت نہ ہوتی تو میں انصار میں سے ہوتا۔','Had there been no emigration I would have been one of the Ansar.'],
[64,88,'نصرت بالرعب مسيرة شهر','میری مدد ایک ماہ کی مسافت کی رعب سے کی گئی۔','I have been given victory through awe at a distance of one months journey.'],
[65,89,'خيركم من تعلم القرآن وعلمه','تم میں بہترین وہ ہے جو قرآن سیکھے اور سکھائے۔','The best amongst you is the one who learns Quran and teaches it.'],
[66,90,'اقرأوا القرآن فإنه يأتي يوم القيامة شفيعا لأصحابه','قرآن پڑھو قیامت کے دن اپنے پڑھنے والوں کا شفاعت کنندہ بن کر آئے گا۔','Recite the Quran for it will come as an intercessor on the Day of Resurrection.'],
[67,91,'تنكح المرأة لأربع: لمالها ولحسبها ولجمالها ولدينها فاظفر بذات الدين','عورت سے چار وجوہ سے نکاح کیا جاتا ہے: مال، حسب، خوبصورتی اور دین۔ تم دیندار کو اختیار کرو۔','A woman is married for four things: wealth lineage beauty and religion. Choose the religious one.'],
[68,92,'أبغض الحلال إلى الله الطلاق','اللہ کے نزدیک سب سے ناپسندیدہ حلال طلاق ہے۔','The most hated lawful thing to Allah is divorce.'],
[69,93,'كفى بالمرء إثما أن يضيع من يقوت','آدمی کے لیے گناہ کے طور پر یہ کافی ہے کہ وہ اپنے اہل و عیال کو ضائع کرے۔','It is sufficient sin for a person to neglect those who depend on him.'],
[70,94,'الطاعم الشاكر بمنزلة الصائم الصابر','شکر گزار کھانے والا صبر کرنے والے روزہ دار کے برابر ہے۔','The one who eats and is grateful is like the one who fasts and is patient.'],
[71,95,'كل غلام مرتهن بعقيقته تذبح عنه يوم سابعه','ہر بچہ عقیقہ کا رہن ہے ساتویں دن اس کی طرف سے ذبح کیا جائے۔','Every child is pledged for its Aqiqah which is sacrificed on the seventh day.'],
[72,96,'سموا باسم الله وكلوا بأيمانكم وكلوا مما يليكم','اللہ کا نام لو دائیں ہاتھ سے کھاؤ اور اپنے سامنے سے کھاؤ۔','Mention the name of Allah eat with your right hand and eat from what is near you.'],
[73,97,'من ذبح قبل الصلاة فليعد','جس نے نماز سے پہلے ذبح کیا وہ دوبارہ ذبح کرے۔','Whoever slaughtered before the prayer should repeat it.'],
[74,98,'كل مسكر حرام','ہر نشہ آور چیز حرام ہے۔','Every intoxicant is forbidden.'],
[75,99,'ما أنزل الله داء إلا أنزل له شفاء','اللہ نے کوئی بیماری نہیں اتاری مگر اس کی شفاء بھی اتاری۔','Allah has not sent down a disease except that He has also sent down its cure.'],
[76,100,'ما يصيب المسلم من نصب ولا وصب ولا هم إلا كفر الله به من خطاياه','مسلمان کو جو تکلیف بیماری یا غم پہنچے اللہ اس سے اس کے گناہ معاف کرتا ہے۔','No fatigue disease or anxiety afflicts a Muslim but Allah will expiate his sins thereby.'],
[77,101,'إن الله جميل يحب الجمال','بیشک اللہ خوبصورت ہے اور خوبصورتی کو پسند فرماتا ہے۔','Indeed Allah is beautiful and loves beauty.'],
[78,102,'ليس منا من لم يرحم صغيرنا ويوقر كبيرنا','وہ ہم میں سے نہیں جو چھوٹوں پر رحم اور بڑوں کا احترام نہ کرے۔','He is not one of us who does not have mercy on our young and respect our elders.'],
[79,103,'الاستئذان ثلاث فإن أذن لك وإلا فارجع','اجازت تین بار مانگو اگر اجازت مل جائے ورنہ واپس چلے جاؤ۔','Permission is to be asked three times. If permitted enter otherwise go back.'],
[80,104,'الدعاء هو العبادة','دعا ہی عبادت ہے۔','Supplication is worship.'],
// Ch81-97
[81,105,'الدنيا سجن المؤمن وجنة الكافر','دنیا مومن کے لیے قید خانہ اور کافر کے لیے جنت ہے۔','This world is a prison for the believer and a paradise for the disbeliever.'],
[82,106,'القدر خيره وشره من الله تعالى','تقدیر کی اچھائی اور برائی اللہ تعالیٰ کی طرف سے ہے۔','Divine Decree its good and evil is from Allah.'],
[83,107,'إنما الأعمال بالنيات','اعمال کا دارومدار نیتوں پر ہے۔','Deeds depend upon intentions.'],
[84,108,'لا يمين في غضب','غصے میں قسم نہیں۔','There is no valid oath taken in anger.'],
[85,109,'ألحقوا الفرائض بأهلها فما بقي فهو لأولى رجل ذكر','میراث اہل کے حوالے کرو جو بچے وہ قریب ترین مرد وارث کا ہے۔','Give the Faraid to those entitled to receive it and what remains is for the nearest male heir.'],
[86,110,'ادرأوا الحدود بالشبهات','شبہات کی وجہ سے حدود کو ٹالو۔','Avert the legal penalties by ambiguities.'],
[87,111,'لا يحل دم امرئ مسلم إلا بإحدى ثلاث','مسلمان کا خون حلال نہیں سوائے تین صورتوں کے۔','It is not permissible to shed the blood of a Muslim except in three cases.'],
[88,112,'من بدل دينه فاقتلوه','جس نے اپنا دین بدلا اسے قتل کرو۔','Whoever changes his religion kill him.'],
[89,113,'رفع عن أمتي الخطأ والنسيان وما استكرهوا عليه','میری امت سے خطا بھول اور اکراہ معاف ہے۔','My Ummah is forgiven for mistakes forgetfulness and what is done under compulsion.'],
[90,114,'إنما الأعمال بالنيات','اعمال کا دارومدار نیتوں پر ہے۔','Actions are judged by intentions.'],
[91,115,'الرؤيا الصالحة من الله والحلم من الشيطان','اچھا خواب اللہ کی طرف سے اور برا خواب شیطان کی طرف سے ہے۔','A good dream is from Allah and a bad dream is from Satan.'],
[92,116,'يتقارب الزمان وينقص العلم ويلقى الشح ويكثر الهرج','زمانہ قریب ہو جائے گا علم کم ہو جائے گا بخل ڈالا جائے گا اور فتنے بڑھیں گے۔','Time will pass quickly knowledge will decrease miserliness will be cast and Harj will increase.'],
[93,117,'من ولي القضاء فقد ذبح بغير سكين','جسے قاضی بنایا گیا اسے بغیر چھری ذبح کیا گیا۔','Whoever is appointed as a judge has been slaughtered without a knife.'],
[94,118,'لا تمنوا لقاء العدو واسألوا الله العافية','دشمن سے ملاقات کی تمنا نہ کرو اللہ سے عافیت مانگو۔','Do not wish to meet the enemy and ask Allah for safety.'],
[95,119,'نضر الله امرأ سمع مقالتي فوعاها فأداها كما سمعها','اللہ اس شخص کو تروتازہ رکھے جس نے میری بات سنی یاد رکھی اور آگے پہنچائی۔','May Allah brighten the face of one who hears my words remembers them and conveys them.'],
[96,120,'تركت فيكم أمرين لن تضلوا ما تمسكتم بهما: كتاب الله وسنة نبيه','میں تمہارے درمیان دو چیزیں چھوڑ رہا ہوں جب تک ان سے چمٹے رہو گے گمراہ نہیں ہو گے: اللہ کی کتاب اور سنت۔','I have left among you two things. You will never go astray as long as you hold on to them: the Book of Allah and the Sunnah.'],
[97,121,'أفضل ما قلته أنا والنبيون من قبلي: لا إله إلا الله وحده لا شريك له','سب سے افضل کلمہ جو میں نے اور مجھ سے پہلے انبیاء نے کہا: لا الہ الا اللہ۔','The best words I and the prophets before me have said: La ilaha illallah.'],
[97,122,'إن لله تسعة وتسعين اسما من أحصاها دخل الجنة','اللہ کے ننانوے نام ہیں جس نے انہیں یاد کیا جنت میں داخل ہوا۔','Allah has ninety-nine names. Whoever memorizes them will enter Paradise.'],
];
